### ISSUE TITLE
Not working in tmux

### ISSUE THREAD

**Issue by oalders** [ryanpcmcquen/fix-vim-pasting#2]
Hi, thanks for this.  I got to your repo from your coderwall comment which said this works in tmux.  I'm seeing it work fine in `vim`, but not `vim` inside of `tmux`. I'm using `tmux` 2.2

**Comment by ryanpcmcquen** [comment]
It works here with `vim` `8.0.1453` and `tmux` `2.6`. What is the behavior you are seeing/steps you are taking?

**Comment by oalders** [comment]
I paste some text in `vim` like:

```
use This;
    foo;
    bar;
```

In `vim` the formatting is preserved.  In `tmux` I see:

```
use This;
    foo;
          bar;
```

I've tried with `vim` `8.0.1092` and `tmux` `2.2` as well as `vim 8.0` and `tmux 2.7`.

**Comment by oalders** [comment]
Relevant dot files: 

https://github.com/oalders/dot-files/tree/master/vim
https://github.com/oalders/dot-files/blob/master/tmux.conf
https://github.com/oalders/dot-files/blob/master/tmux/macos

**Comment by ryanpcmcquen** [comment]
Have you tried removing your `.vimrc` and/or `tmux` configuration temporarily?

**Comment by oalders** [comment]
Thanks for the suggestion.  I started with a new user on a new VM and it worked fine.  I brought back my dot files and then peeled them back until I narrowed it down to this diff:

```
-Plug 'tpope/vim-sensible'
+"Plug 'tpope/vim-sensible'

 source ~/.local_vimrc

@@ -61,7 +61,7 @@ set hlsearch
 set incsearch

 " indents
-set autoindent
+"set autoindent
```

It looks to me like `autoindent` was the culprit.  That's also found here: https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim#L20

As it stands, with those changes paste works for me in both `vim` and `tmux`.  Thanks for your help.

**Comment by ryanpcmcquen** [comment]
@oalders, thanks for tracking that down! I added a note to the README:
https://github.com/ryanpcmcquen/fix-vim-pasting/commit/93273253ebda7679e016b54507b15a846ee093c4

**Comment by ryanpcmcquen** [comment]
Strangely, my `.vimrc` has `autoindent` and still works ...

**Comment by oalders** [comment]
It may have something to do with the version of `vim`.  I can do some more checking.  I'd be interested to track down exactly where the issue is.
